name: Enable auto-merge for labeled PRs
on:
  pull_request:
    types: [labeled, opened, synchronize]
permissions:
  contents: write
  pull-requests: write
jobs:
  enable:
    if: contains(github.event.pull_request.labels.*.name, 'codex-automerge')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
