# .github/workflows/validate-secrets.yml
name: Validate secrets
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any required secret is missing
        run: |
          req=(WIF_PROVIDER GCP_SA_EMAIL GCP_PROJECT GAR_LOCATION GAR_REPO IMAGE_NAME)
          fail=0
          for k in "${req[@]}"; do
            v="${!k}"
            if [ -z "$v" ]; then
              echo "❌ Missing secret: $k"
              fail=1
            else
              echo "✅ $k is set"
            fi
          done
          exit $fail
        env:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
          GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
          GCP_PROJECT:  ${{ secrets.GCP_PROJECT }}
          GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
          GAR_REPO:     ${{ secrets.GAR_REPO }}
          IMAGE_NAME:   ${{ secrets.IMAGE_NAME }}

      - name: Validate WIF provider format
        run: |
          pat='^projects/[0-9]+/locations/global/workloadIdentityPools/[^/]+/providers/[^/]+$'
          [[ "${WIF_PROVIDER}" =~ $pat ]] && echo "✅ WIF_PROVIDER format OK" || { echo "❌ WIF_PROVIDER format invalid"; exit 1; }
        env:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
