# .github/workflows/validate-secrets.yml
name: Validate secrets
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fail fast if any secret is missing
        run: |
          req=(WIF_PROVIDER GCP_SA_EMAIL GCP_PROJECT GAR_LOCATION GAR_REPO IMAGE_NAME)
          fail=0
          for k in "${req[@]}"; do
            v="${!k}"
            if [ -z "$v" ]; then
              echo "❌ Missing secret: $k"
              fail=1
            fi
          done
          exit $fail
        env:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
          GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
          GCP_PROJECT:  ${{ secrets.GCP_PROJECT }}
          GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
          GAR_REPO:     ${{ secrets.GAR_REPO }}
          IMAGE_NAME:   ${{ secrets.IMAGE_NAME }}

      - name: Validate WIF provider format (no value printed)
        run: |
          pat='^projects/[0-9]+/locations/global/workloadIdentityPools/[^/]+/providers/[^/]+$'
          if [[ "${WIF_PROVIDER}" =~ $pat ]]; then
            echo "✅ WIF_PROVIDER format looks good"
          else
            echo "❌ WIF_PROVIDER format is invalid"
            exit 1
          fi
        env:
          WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
